// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pbx$0 from "./pbx/models.js";

export interface PinApplyResult {
    "folio": number;
    "rows": pbx$0.PinRow[] | null;
    "applied": number;
    "skipped": number;
    "failed": number;
}

export interface PinPreview {
    "listID": number;
    "info": pbx$0.CSVInfo;
    "rows": pbx$0.PinRow[] | null;
    "new": number;
    "existing": number;
    "noDesc": number;
    "errors": number;
}

export interface ProfileView {
    "profile": pbx$0.Profile;
    "has": SecretFlags;
}

export interface ProfilesView {
    "active": string;
    "profiles": ProfileView[] | null;

    /**
     * backup path of a corrupt profiles file, reported once
     */
    "recovered": string;
}

export interface SecretFlags {
    "api": boolean;
    "ssh": boolean;
    "sshKey": boolean;
    "ami": boolean;
}

export interface UpdateInfo {
    "current": string;
    "latest": string;
    "available": boolean;
}
