// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PinService is F-02: add PINs from a CSV to an existing PIN list of the active PBX.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pbx$0 from "./pbx/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Apply(listID: number): $CancellablePromise<$models.PinApplyResult> {
    return $Call.ByID(2790334538, listID);
}

/**
 * ApplyPortal runs the portal's own Apply with the profile's API credentials (F-01). It reloads
 * the PBX with ALL outstanding portal changes; the UI only calls it after a two-step confirmation.
 */
export function ApplyPortal(): $CancellablePromise<string> {
    return $Call.ByID(3145290304);
}

export function Lists(): $CancellablePromise<pbx$0.PinList[] | null> {
    return $Call.ByID(2027479031);
}

/**
 * PickCSV opens the native file dialog; "" means the user cancelled.
 */
export function PickCSV(): $CancellablePromise<string> {
    return $Call.ByID(3111355357);
}

export function Preview(listID: number, path: string, includeEmpty: boolean): $CancellablePromise<$models.PinPreview> {
    return $Call.ByID(2029807710, listID, path, includeEmpty);
}
