// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService owns the profile store. The frontend never receives stored secrets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pbx$0 from "./pbx/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(4049605311, id);
}

export function List(): $CancellablePromise<$models.ProfilesView> {
    return $Call.ByID(3633778972);
}

/**
 * NextFolio issues the work-order number for the run about to start.
 */
export function NextFolio(): $CancellablePromise<number> {
    return $Call.ByID(952439514);
}

/**
 * Save creates (empty ID) or updates a profile. Empty secret fields keep the stored secrets.
 */
export function Save(p: pbx$0.Profile, sec: pbx$0.Secrets): $CancellablePromise<pbx$0.Profile> {
    return $Call.ByID(2176397137, p, sec);
}

export function SetActive(id: string): $CancellablePromise<void> {
    return $Call.ByID(3395228430, id);
}

/**
 * Test checks the saved profile's enabled channels (not unsaved form edits).
 */
export function Test(id: string): $CancellablePromise<pbx$0.ChannelResult[] | null> {
    return $Call.ByID(4070177200, id);
}

/**
 * TrustFingerprint pins the certificate ("api") or host key ("ssh") the user just accepted.
 */
export function TrustFingerprint(id: string, channel: string, fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(1998372302, id, channel, fingerprint);
}
