// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService replaces the running exe with the latest GitHub release.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply downloads the release found by Check, verifies checksums.txt and swaps the exe.
 */
export function Apply(): $CancellablePromise<void> {
    return $Call.ByID(653261396);
}

/**
 * Check never reports updates for local "dev" builds.
 */
export function Check(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(688929688);
}

/**
 * Restart launches the (new) exe and quits this process.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(3205679179);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1824574892);
}
