// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AMIConfig {
    "enabled": boolean;
    "port": number;
    "user": string;
}

export interface APIConfig {
    "enabled": boolean;
    "baseURL": string;
    "user": string;
    "certSHA256": string;
}

/**
 * ChannelResult is one channel's outcome in a connection test.
 */
export interface ChannelResult {
    /**
     * "api", "ssh" or "ami"
     */
    "channel": string;
    "skipped": boolean;
    "ok": boolean;
    "message": string;
    "millis": number;
    "fingerprint": string;
    "fingerprintChanged": boolean;
}

export interface Profile {
    "id": string;
    "name": string;
    "host": string;
    "api": APIConfig;
    "ssh": SSHConfig;
    "ami": AMIConfig;
}

export interface SSHConfig {
    "enabled": boolean;
    "port": number;
    "user": string;
    "keyPath": string;
    "hostKeySHA256": string;
}

/**
 * Secrets travel UI -> Go only. An empty field means "keep what is stored".
 */
export interface Secrets {
    "api": string;
    "ssh": string;

    /**
     * passphrase of the SSH key file
     */
    "sshKey": string;
    "ami": string;
}
